name: ci

on: push

jobs:
  build_release:
    name: build and release
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python 3.6 for build process
        run: |
          curl -o python-3.6.8.exe https://www.python.org/ftp/python/3.6.8/python-3.6.8.exe
          python-3.6.8.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0
          mkdir c:\venv
          c:\Python36\python -m venv c:\venv
          cd C:\venv
          powershell venv\Scripts\activate
          python -m pip install Sphinx==3.5.4
          
      - name: Prepare and build python 3.9 from source
        run: |
          curl -o C:\python.tar.xz https://www.python.org/ftp/python/3.9.14/Python-3.9.14.tar.xz
          tar -xvzf C:\python.tar.xz -C C:\venv
          cd C:\venv
          buildrelease.bat -x86 -x64 --skip-pgo
          dir
          
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            PCbuild/win32/*
