name: ci

on: push

jobs:
  build_release:
    name: build and release
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install msbuild 140 tools
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install visualcpp-build-tools -version 14.0.25420.1 -y

      - name: Download Python 3.6
        run: |
          curl -o python-3.6.8.exe https://www.python.org/ftp/python/3.6.8/python-3.6.8-amd64.exe

      - name: Install Python 3.6
        shell: cmd
        run: |
          python-3.6.8.exe /quiet PrependPath=1 Include_test=0
          dir %LocalAppData%\Programs\Python
          
      - name: Prepare Python 3.6 venv
        shell: cmd
        run: |
          mkdir C:\venv
          %LocalAppData%\Programs\Python\Python36\python.exe -m venv c:\venv
          dir C:\venv
          
      - name: Install pip dependency
        shell: cmd
        working-directory: C:\venv
        run: |
          .\Scripts\pip3.exe install Sphinx==3.5.4
          
      - name: Download Python 3.9 source
        run: |
          curl -o C:\python.tar.xz https://www.python.org/ftp/python/3.9.14/Python-3.9.14.tar.xz

      - name: Extract Python 3.9 source directly into venv
        shell: cmd
        run: |
          "C:\Program Files\Git\usr\bin\tar.exe" -xf /c/python.tar.xz -C /c/venv --strip-components=1
          dir C:\venv

      - name: Patch Python 3.9 source
        run: |
          cmd.exe /C patch.bat

      - name: Build Python 3.9 from source
        run: |
          cmd.exe /C build.bat
          dir C:\venv\PCbuild\amd64
          
      - name: Compress release
        run: |
          mkdir C:\output
          Compress-Archive -Path C:\venv\PCbuild\amd64\* -DestinationPath C:\output\python3.9.zip  
          dir C:\output
          
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            C:/output/*
